view:
  reload: true
  engine:
    "django" :
      path: "views/"
      suffix: ".tpl"
    "html" :
      path: "views/"
      suffix: ".html"
session:
  name: "gosessionid"
  expires: 0
port: 2017
pprof:
  open: true
  port: 6060
  route: "/debug/pprof/*action"
log_path: "logs"
charset: "UTF-8"
hashkey: "the-big-and-secret-fash-key-here"
blockkey: "lot-secret-of-characters-big-too"
backend_route_party: "/backend/"